plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.5-beta'
}

tasks.named('wrapper', Wrapper) {
    distributionType = Wrapper.DistributionType.BIN
}

version = '1.0.0'
group = 'com.example.ragdollmod'

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

neoForge {
    version = '21.1.65'

    parchment {
        mappingsVersion = '2024.07.28'
        minecraftVersion = '1.21.1'
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'ragdollmod'
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'ragdollmod'
        }
    }

    mods {
        ragdollmod {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation "maven.modrinth:sableragdolllib:0.8-alpha"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}