modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="ragdollmod"
version="1.0.0"
displayName="Ragdoll Mod"
authors="hapermeh"
description="Ragdoll physics and synchronization library."