modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="sableragdolllib"
version="1.0.0"
displayName="Sable Ragdoll Lib"
authors="hapermeh"
description="Ragdoll physics and synchronization library."